{"uuid":"ea164fde-cfee-4068-8f73-e4b7a3cf27d6","historyId":"6cc384dd149deee2c7f18f4d8de1e9d4","fullName":"TestCases.TC01_CreateSavingsAccountWith5000AmtAndCloseTheAccount.runTest","labels":[{"name":"package","value":"TestCases.TC01_CreateSavingsAccountWith5000AmtAndCloseTheAccount"},{"name":"testClass","value":"TestCases.TC01_CreateSavingsAccountWith5000AmtAndCloseTheAccount"},{"name":"testMethod","value":"runTest"},{"name":"parentSuite","value":"Default suite"},{"name":"suite","value":"Default test"},{"name":"subSuite","value":"TestCases.TC01_CreateSavingsAccountWith5000AmtAndCloseTheAccount"},{"name":"host","value":"Priyaramasami-Personal-11255"},{"name":"thread","value":"15476@Priyaramasami-Personal-11255.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"runTest","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Test Failed: Exception occurred -> C:\\Users\\priya\\Finacle\\Core\\CoreBanking\\Resource\\TestData.xlsx (The process cannot access the file because it is being used by another process)","trace":"java.lang.AssertionError: Test Failed: Exception occurred -> C:\\Users\\priya\\Finacle\\Core\\CoreBanking\\Resource\\TestData.xlsx (The process cannot access the file because it is being used by another process)\r\n\tat org.testng.Assert.fail(Assert.java:111)\r\n\tat CASA.CreateSavingsAccount.execute(CreateSavingsAccount.java:463)\r\n\tat TestCases.TC01_CreateSavingsAccountWith5000AmtAndCloseTheAccount.runTest(TC01_CreateSavingsAccountWith5000AmtAndCloseTheAccount.java:77)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:741)\r\n\tat org.testng.TestRunner.run(TestRunner.java:616)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:421)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:312)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1208)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1112)\r\n\tat org.testng.TestNG.run(TestNG.java:1079)\r\n\tat org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)\r\n\tat org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)\r\n\tat org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)\r\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1751016216737,"stop":1751016266297}